version: "3.9"

services:

  db:
    
    build: ./database
    
    container_name: IMS-db
    
    restart: always
    
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/initdb.sql

  backend:
    build: ./backend

    container_name: IMS-backend

    restart: always

    depends_on:
      - db
    
    environment:
      FLASK_ENV: development
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      FLASK_DEBUG: "True"
      DATABASE_URL: postgresql://postgres:1234@db:5432/inventory_management_db
      TEST_DATABASE_URL: postgresql://postgres:1234@db:5432/inventory_db_test

    ports:
      - "5000:5000"

  frontend:
    build: ./frontend

    container_name: IMS-frontend

    restart: always

    depends_on: 
      - backend

    ports:
      - "3000:3000"

  nginx:
    build: ./nginx

    container_name: IMS-nginx

    restart: always

    depends_on:
      - frontend
      - backend

    ports:
      - "80:80"
  
volumes:
  db_data: